name: Generate TamilMV RSS

permissions:
  contents: write

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 mins
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install cloudscraper beautifulsoup4 lxml

      - name: Run scraper
        run: |
          python tamilmv_rss.py

      - name: Commit & Push RSS if changed
        run: |
          git config --global user.name "rss-bot"
          git config --global user.email "rss@bot.com"
          git add tamilmv.xml
          git diff --cached --quiet || git commit -m "Update TamilMV RSS"
          git push
